[package]
name = "skycurrent"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2"
dunce = "1.0"
bitflags = "2.9.0"
# iceoryx2 = { version = "0.5.0", features = ["logger_tracing"] }
# iceoryx2-bb-system-types = "0.5.0"
# iceoryx2-bb-container = "0.5.0"
iceoryx2 = { git = "https://github.com/eclipse-iceoryx/iceoryx2.git", rev = "b7fc3bf" }
iceoryx2-bb-system-types = { git = "https://github.com/eclipse-iceoryx/iceoryx2.git", rev = "b7fc3bf" }
iceoryx2-bb-container = { git = "https://github.com/eclipse-iceoryx/iceoryx2.git", rev = "b7fc3bf" }
